# Generated by Django 3.0.5 on 2020-04-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('game', models.PositiveSmallIntegerField(choices=[(1, 'pres')])),
                ('players', models.IntegerField(default=0)),
                ('max_players', models.IntegerField()),
                ('ingame', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
