# Generated by Django 3.0.5 on 2020-04-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='game',
            field=models.CharField(choices=[('PRES', 'President')], max_length=4),
        ),
    ]
