# Generated by Django 3.0.5 on 2020-04-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame_president', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GamePlayer',
            new_name='Player',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='play_turn',
            new_name='max_players',
        ),
        migrations.AddField(
            model_name='game',
            name='starting_player',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='game',
            name='consecutive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_card',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='game',
            name='order_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='play_stack',
            field=models.IntegerField(default=-1),
        ),
    ]
